# 服务配置
server:
  address: localhost
  port: 8045
  tomcat:
    uri-encoding: UTF-8



# 数据库设置
spring:
  datasource:
    password: Jia1987
    username: root
    url: jdbc:mysql://localhost:3306/management?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver




# 图片上传的路径
web.upload-path: /Users/liangjiazhang/Documents/uploads

